  services:
    nginx:
      container_name: nginx
      networks:
        - inception
      depends_on:
        - wordpress
      build:
        context: nginx
        dockerfile: Dockerfile
      env_file: .env
      volumes:
        - wordpress:/var/www/wordpress
        - adminer:/var/www/adminer
      ports:
        - "443:443"
      restart: on-failure
    mariadb:
      container_name: mariadb
      networks:
        - inception
      build:
        context: mariadb
        dockerfile: Dockerfile
        args:
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
      env_file: .env
      volumes:
        - mariadb:/var/lib/mysql
      restart: on-failure
      expose:
        - "3306"
    wordpress:
      container_name: wordpress
      networks:
        - inception
      depends_on:
        - mariadb
        - redis
      build:
        context: wordpress
        dockerfile: Dockerfile
      env_file: .env
      volumes:
        - wordpress:/var/www/wordpress
      restart: on-failure
      expose:
        - "9000"
    redis:
      container_name: redis
      networks:
        - inception
      build:
        context: bonus/redis
        dockerfile: Dockerfile
      restart: on-failure
      expose:
        - "6379"
    adminer:
      container_name: adminer
      networks:
        - inception
      build:
        context: bonus/adminer
        dockerfile: Dockerfile
      volumes:
        - adminer:/var/www/adminer
      restart: on-failure
      expose:
        - "9001"
    ftp:
      container_name: ftp-server
      networks:
        - inception
      build:
        context: bonus/FTP
        dockerfile: Dockerfile
        args:
          - FTP_PW=${FTP_PW}
      env_file: .env
      volumes:
        - wordpress:/var/www/ftp/wordpress
      restart: on-failure
      ports:
        - "21:21"
        - "21000-21010:21000-21010"
    static-site:
      container_name: static-site
      networks:
        - inception
      build:
        context: bonus/static-site
        dockerfile: Dockerfile
      restart: on-failure
      expose:
        - "80"
  volumes:
    wordpress:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/igrousso/data/wordpress'
    mariadb:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/igrousso/data/mariadb'
    adminer:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/igrousso/data/adminer'
  networks:
    inception:
      driver: bridge